version: 2

project_name: ordercli

changelog:
  disable: true

builds:
  - id: ordercli
    main: ./cmd/ordercli
    binary: ordercli
    env:
      - CGO_ENABLED=0
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64

archives:
  - builds:
      - ordercli
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt
